### ISSUE TITLE
BungeeCord IP Forwarding

### ISSUE THREAD

**Issue by EthanWu13** [SpigotMC/BungeeCord#1312]
I can't connect to my server that is connected to the bungeecord server with the ip port. (Like localhost:25566) I have all the latest builds I just downloaded it today. I did all the configuation and it still doesn't work. Do I have to have to set true on the bungeecord: true in spigot.yml? Do I have to open all my server?

**Comment by dualspiral** [comment]
@EthanWu13 - if you can't connect because you are using a Forge 1.8 *client* with BungeeCord and Spigot 1.8 with IP forwarding on, then this is the same as issue #1277 and I've written a PR (#1318) to work around this for now.

If not, then this is a support issue, and should be directed to the Spigot Forums instead - you'll likely get more help there.

**Comment by EthanWu13** [comment]
Is optifine a forge client
