### ISSUE TITLE
Bungeecord vanilla lobby in combination with ichun morph mod players stay morphed

### ISSUE THREAD

**Issue by Superjo149** [SpigotMC/BungeeCord#1323]
For those who don't know the morph mod from iChun, it's a mod that allow you to morph(transform) into an entity you killed. This works both for vanilla and modded entities.

The issue is tho that when players go back to the vanilla lobby server, if they were morphed into a vanilla entity. They are still morphed into this in the lobby. So they still have the ability to fly.

Is this possible to fix?

**Comment by dualspiral** [comment]
This is an issue with the mod, so you should contact the mod author. The mod should listen for FML Mod Id Mapping event I believe and perform a reset then (though I'm not sure if it gets fired when going to a vanialla server, though I'm fairly sure it should be). Alternatively, you could in theory write a Bungee plugin that sends the demorph packet for you on a server switch.

Not something that be fixed by Bungee by itself.

**Comment by Superjo149** [comment]
Ok thank you very much for replying anyways.
