### ISSUE TITLE
[Feature]BungeeCord Passwords

### ISSUE THREAD

**Issue by j0ach1mmall3** [SpigotMC/BungeeCord#1354]
Hello,
Wouldn't it be a nice idea for Bungeecord to use passwords?
That way, a Bungeecord proxy can only connect to a Spigot server that has the same password, specified in the config file.
This would prevent the exploit using the 'Home-Setup' proxy connecting to Backend Spigot servers, as one first needs to know the server password.
Thanks for reading this thread.
Post suggestions/feedback below :)

**Comment by portalBlock** [comment]
I see a problem of a false sense of security with that, the 'Home-Setup' is useless against firewalls. Since the connection between Spigot and Bungee is unencrypted it might actually make it easier for people to get in because server owners may be less likely to setup a firewall. This is just my 2 cents worth.

**Comment by kamcio96** [comment]
try iptables or plugin which accept connections from one ip (bungee ip)

**Comment by skycatcher** [comment]
you can set "server-ip: 127.0.0.1" in server.properties
