### ISSUE TITLE
Players kick on join another player.

### ISSUE THREAD

**Issue by UnioDex** [SpigotMC/BungeeCord#1381]
Players are kicking when another person try join their accounts. 

Issue video:
https://www.youtube.com/watch?v=2FfH3390GZo

Im using BungeeCord #1049

**Comment by Jannik8500** [comment]
It's a Bukkit plugin, not a BungeeCord issue. 
Which plugins you you using?

**Comment by UnioDex** [comment]
This issue is new. Formerly not error. But after update there is.

Plugins:
[18:38:06 INFO]: Plugins (24): UnioCommandProtect, IPSecurity, GroupManager, WorldEdit, TimedCommands, Skript, PluginManager, BanManager, Vault, InputGuiAPI, ProtocolLib, Multiverse-Core, MyCommand, PingPlayer, WorldGuard, CleanroomGenerator, Essentials, EssentialsProtect, EssentialsSpawn, EssentialsChat, EssentialsAntiBuild, AuthMe

**Comment by TagCraftMC** [comment]
I can confirm this is an issue and is not due to bungee/bukkit plugins.
I have tested this on a local set up running Bungee #1049 and two other spigot severs (latest 1.7.10) with 0 plugins on them and this issue still persists. (PlayerA is connected to Bungee and someone tries to connect as PlayerA as well, the first PlayerA is kicked)
Rolling back to our previous version of bungee (#1038) fixes the issue.

Ill do so more tests to see what version of bungee this issue started in.

**Comment by md-5** [comment]
1) Client version
2) Bungee version
3) Config.yml
4) Update Bungee
