### ISSUE TITLE
1.7 support broken?

### ISSUE THREAD

**Issue by md-5** [SpigotMC/BungeeCord#1474]
http://www.spigotmc.org/threads/empty-packet-protocol-bug-1-7-x.67058/#post-739343

**Comment by thinkofdeath** [comment]
Not sure why 1.7 would be sending an empty packet because it wouldn't even have a packet id so would fail at later stages. 

On another note maybe its time to drop 1.7 support? It's been almost a year now and we were originally going to drop it earlier.

**Comment by Katelyn-SN** [comment]
Many of us modded server owners and regular server owners still use 1.7 as primary due to various issues. Many issues are present in bungee for 1.7 (Logout issues, Packet issues not related to forge, Attacks and lockups) at this point it would be a bad idea as more of us use 1.7 instead of 1.8 for pretty good reasons.

**Comment by kamcio96** [comment]
so, maybe other branch with 1.7 and only support bugs?

**Comment by Puddanator** [comment]
I would give it 1 or 2 more months as the people using 1.7 is going down more and more each month. 1.9 is starting to get teasers now and really, 1.7 should be behind us.

**Comment by Katelyn-SN** [comment]
When it comes to modded services 1.7 will be the standard for quite a bit longer there is no solid platform for server owners to use for 1.8 and most mods are just not updating for 1.8.

**Comment by LordAkkarin** [comment]
Well dropping support for it does not mean that older versions will stop working. You are free to use an older version and technically it would still be possible to backport security relevant changes if needed (just not feature additions and such).

**Comment by bolda500** [comment]
In my opinion, if previously were created and corrected serious errors in proxy for versions 1.5.2-1.6.4, in this case if it has been patched fairly serious security hole, should be created a workaround for this problem and created the possibility of further cooperation 1.7-1.8 version of proxy. Independent developers have certainly done it, if they wanted to take advantage of the vulnerabilities patched but in the same time don't lose a large resource of players from version 1.7.x

**Comment by Shevchik** [comment]
Actually empty packet is possible.
Minecraft server inbound pipeline consists of 2 elements, the splitter, and the decoder. Splitter will read 0 length packet and will pass an empty byte buf to decoder. Decoder has an isReadable check, so that empty packet won't be handled at all. @md-5 
The conditions under which the empty packet is sent are unclear, but that happens sometimes for some reason.

**Comment by LordAkkarin** [comment]
@Shevchik Bungee has handled this the same way. However it was reported that empty packets can cause quite a lot of load (due to the fact that the frame decoder keeps executing for every single byte). The fix I proposed a while back is to deny packets with a packet size of 0 (e.g. the header consisting of one byte with all bits unset).

However I do not quite understand why Minecraft 1.7 would need to send entirely empty packets (aka consisting of only one empty byte) back and forth. If this is really the cause (which would be really stupid - Thanks Mojang) it could easily be fixed by discarding the data (e.g. not adding a result value back to the pipeline) rather than terminating the connection. However the current solution seems to work fine for 1.8 (and as I mentioned before I still don't quite understand why the hell 1.7 would send an entirely empty packet without any meaning; seriously it doesn't even include a packetID) and makes attacks far harder than they were before (even though this issue should not cause any major issues on servers with reasonable processing power).

**Comment by PsychoLynx** [comment]
Hey! I see the issue is closed, but with the problem persists for me at least in the build 1071 (newest) of BungeeCord?
