### ISSUE TITLE
Incompatible FML modded server.

### ISSUE THREAD

**Issue by florian96** [SpigotMC/BungeeCord#1505]
Hey the Connection works with a FML modded server but in the Server info is this: 
![image](https://cloud.githubusercontent.com/assets/9999676/8242315/cbfb4b14-160e-11e5-9eee-05f985fd4fe6.png)

**Comment by 20zinnm** [comment]
I'd say it's an issue with the proxy, because with BungeeCord acting as the middle-man it might not communicate correctly. I could be and likely am wrong but that's as far as I can guess.

**Comment by florian96** [comment]
If bungeecord has a Configuration with a List of the mods, then it is Fixed.

**Comment by Janmm14** [comment]
But can't the mod list change based on the backend server?

**Comment by Katelyn-SN** [comment]
The issue is that the modInfo object is created but never wrote to. I don't believe @dualspiral ever finished that part probably for a reason. It would nice for it to be forced host based and to be able to get modList's from the server that we could use in plugins however that's not the case.

**Comment by dualspiral** [comment]
Yes, I create an empty list at https://github.com/SpigotMC/BungeeCord/blob/9cf57ca929934fb58463a1e654e81ec72451d894/api/src/main/java/net/md_5/bungee/api/ServerPing.java#L98 so we send a conforming FML ping packet. It was never intended to be any more than that - let me explain.

When I did this originally, returning an empty mod list gave the "green checkmark". This was generally sufficient, because most server owners would be using a vanilla lobby along with a series of different mod packs as secondary servers, so trying to ping them all would have been a nightmare. This was the simplest solution that covered most cases, which is why I went with it. If you hovered over the checkmark, you'd see no mods were presents, but FML would be totally fine with it.

Of course, now that isn't the case. We're seeing a red X instead - probably because we aren't sending the Forge, FML and MCP mods in the list and so (at least now) FML figures it's not going to be able to connect. Unfortunately, the version numbers are important as well - and that's the hard part.

If you used a forced host and enabled ping passthrough, it would work fine, though this is generally not desired - https://github.com/SpigotMC/BungeeCord/blob/9cf57ca929934fb58463a1e654e81ec72451d894/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L225

Otherwise, the bit that would need to be worked on would start with https://github.com/SpigotMC/BungeeCord/blob/9cf57ca929934fb58463a1e654e81ec72451d894/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L231 I believe, at a quick glance. However, I'd recommend against trying to ping a backend server each time - instead preferring to cache information from another server.

The alternative is to just mark the server as Vanilla by removing the extra infomation - but this will just cause server owners to say that it looks vanilla, rather than modded. Maybe we could talk to the Forge guys and ask if we can add a "Bungee" or "ServerNetwork" server type into FML - so the client will display it the server as such.

We could think about firing an event instead (maybe move the ServerPingEvent) and allow mod lists to be added by an external plugin - but then that becomes a problem for server owners who don't have a good grasp on how FML _really_ works - yeah, actually, probably not a good idea!
