### ISSUE TITLE
Force binding to IP in server.properties

### ISSUE THREAD

**Issue by Starfire1337** [SpigotMC/BungeeCord#1518]
I've noticed that in shared hosting environments, BungeeCord is able to bind to any IP and port available on the node, and not just the IP/port assigned to the server. This can create a problem where customers can interfere with one another's services by binding to random IP's or ports using bungee.

What I propose is that on startup, bungee should check to see if the file server.properties exists, and bind to the IP in server.properties if it exists. This is because Multicraft will always force the IP and port assigned to the server into server.properties.

**Comment by LordAkkarin** [comment]
Fixing this problem is entirely up to the provider.

There is no point in fixing this issue on our side especially since most providers will allow you to add custom jars which could be stripped of this feature (or contain an entirely different program).

**Comment by minecrafter** [comment]
I feel this functionality would be more confusing than helpful, never mind the fact that the binding is configurable in `config.yml`, which a user would have to edit anyway.

Anyway, it's not even recommended to run BungeeCord on shared hosting environments using software like Multicraft due to security issues, and the fact that BungeeCord is very different from Bukkit/Spigot.
