### ISSUE TITLE
BungeeCord error

### ISSUE THREAD

**Issue by Xayanix** [SpigotMC/BungeeCord#1521]
Fixed

**Comment by LordAkkarin** [comment]
As the error clearly states, Bungee has exceeded the Garbage Collection overhead limit. This usually happens when the Java process gets close to using up all of it's memory without having an option of allocating enough memory to fit the new data.

TL;DR: Assign more memory. Bungee should need around 512MB per 500 players (this value might be higher depending on the plugins you run).

**Comment by Xayanix** [comment]
Hi LordAkkarin, 
I had 2GB allocated.

screen -S "Bungee" java -Xmx2G -jar BungeeCord.jar

**Comment by Xayanix** [comment]
These bots are glitching Tab complete event, i setCancelled(true) these and cant kill my server.

**Comment by Paulomart** [comment]
Maybe bungee could add a throttle for tab complets?

**Comment by Xayanix** [comment]
I will try.

**Comment by Xayanix** [comment]
@md-5 

UpstreamBridge.java
Fixed by adding throotle: http://pastebin.com/SwB1tEzq

**Comment by LordAkkarin** [comment]
@Xayanix You should be using GitHub's pull request feature instead. Random pastebins with codes are most likely ignored. Additionally your code is not even close to following the code style (why the hell are you using the wrapped primitive instead of using a regular long when the value is never null anyways?).

**Comment by Xayanix** [comment]
Im not so advanced programmer like You :(

**Comment by LordAkkarin** [comment]
@Xayanix Don't worry. I've already re-wrote it and created a Pull Request for this issue (see #1522).

**Comment by Xayanix** [comment]
up

fixed that
