### ISSUE TITLE
io.netty.handler.codec.CorruptedFrameException: Empty Packet!

### ISSUE THREAD

**Issue by JANEXLEBJAKOT** [SpigotMC/BungeeCord#1599]
http://pastebin.com/gXV5s58z
Only 1.7 clients problem

**Comment by ninja-** [comment]
that's something @md-5 refused to fix upstream so you need to fix it yourself by removing that check. I also can't run a server without fixing this so I am on my own.

**Comment by md-5** [comment]
"Removing that check" is not a fix for anything. If you can prove why/when a legitimate client is sending a packet with no data, then we can talk.

**Comment by ninja-** [comment]
@md-5 it's not the client....it's the server

**Comment by LemADEC** [comment]
This issue happens with ProtocolSupport plugin when a 1.7.10 client (Vanilla or Forge) connects to a Spigot 1.8.8 client.

**Comment by ninja-** [comment]
Oh. Thats correct lamadec

**Comment by LemADEC** [comment]
According to ProtocolSupport plugin author, it's normal behavior of 1.7.10 clients: https://github.com/Shevchik/ProtocolSupport/issues/66

**Comment by Shevchik** [comment]
After some investigation i found the reason for it.
When you skip writing a packet in MessageToByteEncoder netty still writer buffer, but empty one.
I was sure that it was client doing, but that only was because i was using modified debug client that skipped writing some packets (packet loss simulation).
But the actual reason is server skipping wiritng 1.8 packets to 1.7.10 client, which causes empty packets.

**Comment by LemADEC** [comment]
Excellent!
So what's the best way to fix that bug?

**Comment by Shevchik** [comment]
Patch PacketPrepender to do nothing if input buffer is not readable

**Comment by md-5** [comment]
It's a server side bug.
