### ISSUE TITLE
Everyone has the same IP

### ISSUE THREAD

**Issue by TrainsPlayMinecraft** [SpigotMC/BungeeCord#1609]
Hi, on my server everyone has the same IP. Any help?

**Comment by yawkat** [comment]
enable ip forwarding.

**Comment by TrainsPlayMinecraft** [comment]
I have.

**Comment by kamcio96** [comment]
and enable it in spigot.yml

**Comment by Janmm14** [comment]
For configurations please use pastebin.com and put here the link next time

**Comment by ThePhineas** [comment]
Okay, seeing as nobody has helped, I'll tell you the issue you're having. You have some type of DDoS protection or reverse proxy that isn't blocking you from seeing people's IPs since everyone is connecting through the DDoS protection, and every time you try to see someone's IP, it tells you the IP of the reverse proxy/DDoS protection server. Did you know you had DDoS protection or did it just come with the host? If so, please tell me the name of the host and I will be able to help you further to solve this issue.

**Comment by TrainsPlayMinecraft** [comment]
Thanks everybody, but it's been fixed now.
:)

**Comment by ThePhineas** [comment]
@TrainsPlayMinecraft What was the issue?

**Comment by TrainsPlayMinecraft** [comment]
I needed to enable BungeeCord in my servers config.

**Comment by prozhong** [comment]
@ThePhineas 
I'm using one Nginx ( tcp reverse proxy module ) as DDos protection.
Could you please give some advice on ip-forwarding?

**Comment by Janmm14** [comment]
@proxhong
Currently no solution exists.
You could modify bungeecord to have the same method as spigot has and let nginx reverse peoxy changing the handshake (?) packet similar to bungee (bungee discards and sends own I think)

However I do not get why to use nginx as reverse proxy. Just put bungee on a ddos protected machine.
