### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by GammerGemplay** [SpigotMC/BungeeCord#1756]
When i use Bungeecord, and i want it to have the default server, to the server i also use for host bungeecord! But when i try to join i getting kicked and it says: You are already connected to that server?? what shall i do?﻿

https://gyazo.com/6998e0618fce665f4d0b7504309d14f6

and the issue

https://gyazo.com/ae1ba37d2a1eaf355a366b6291f707ca

**Comment by md-5** [comment]
Your bungee and server ports are the same, so bungee is connecting to itself. Fix this.

**Comment by GammerGemplay** [comment]
How shall i fix that?

**Comment by kamcio96** [comment]
http://scr.hu/1s1h/nkiv6
Same ip
In lobby you have to have spigot ip
And:
```
listeners:
  ...
  host: 0.0.0.0:25565
```

**Comment by GammerGemplay** [comment]
Like this?
listeners:
  37.187.156.206:50232
  host: 0.0.0.0:25565

**Comment by GammerGemplay** [comment]
Or can u send your a example..

**Comment by willies952002** [comment]
I have a simple question: are you using shared hosting?

**Comment by GammerGemplay** [comment]
What is shared hosting?

**Comment by willies952002** [comment]
A shared host is where there are multiple clients running servers on the same machine that is owned by a company. An example of a shared host would be MCProHosting.

here's the easiest way of knowing:
Shared = No terminal access to the box.
Self-Hosted = Root terminal access to the box.

**Comment by GammerGemplay** [comment]
i use OwnageHosting so i dont really now..

**Comment by GammerGemplay** [comment]
know*

**Comment by willies952002** [comment]
OwnageHosting is a shared host, which means you will need to purchase separate servers for running bungeecord and every server instance.

Also.. since you do have a shared host, it's not recommended that you have your bungee listen to `0.0.0.0:25565` since that is most likely already assigned to another client, so it's most likely a best to have your bungee instance listen to `0.0.0.0:50232` and have your servers listen on which ever port your host assigns to them.

**Comment by GammerGemplay** [comment]
So i shall buy a server for running Bungeecord and a server for the hub??
