### ISSUE TITLE
High CPU usage even after attack is stopped.

### ISSUE THREAD

**Issue by smartmadio** [SpigotMC/BungeeCord#1762]
My server had been attacked by bot attack yesterday.The bot attack last only 3 seconds,20 bots joined in server during the attack.After the attack is finished,the bungeecord's CPU usage is still 100% and won't go down.
I've tried cutting down all network connections with bungeecord,but bungeecord displays the bots are still online(using the command /glist) and but normal players are all offline.It's really strange.
How do all the bots are still online in bungeecord after all network connections are cut down?Is this a bug?
(All bots joined in at one time.After the bots joined in ,the bungeecord's CPU usage reach 100% immediately.)
Hardware info about my server:E5-2666V3/32G ram.

**Comment by willies952002** [comment]
I recommend restarting your Bungeecord to get the bots off the network. If they return, it's a good idea to take note of their IP addresses and put up a firewall so they cannot reconnect again.

**Comment by smartmadio** [comment]
Yeah,I've put their IP into firewall blacklist,but they could change their IP using various of ways.(VPN,proxy,ADSL users could get a new IP by redial again.)

**Comment by smartmadio** [comment]
And my question is why bungeecord won't disconnect the bots even if their network connection have been cut down.It's really strange.

**Comment by Janmm14** [comment]
Waited 1 minute? How do you see that they are still connected? Are they connected to the underlying cb/spigot server or are they only shown in /glist output?

**Comment by smartmadio** [comment]
They only shown in /glist.No bots could be found in any of the spigot servers.

I'm quite sure I'm using the last bungeecord version.I've been attacked for two times,after the first attack,I visted ci.md-5.net and downloaded the latest version of bungeecord.

**Comment by XNoki200010** [comment]
Same here.

The CPU is 100% and the whole Server is lagging.
Also the RAM is full.

**Comment by FurmigaHumana** [comment]
If you have a significant amount of new connections that disconnects very after connecting (bot attack, invalid connections or something like that), bungeecord will overload the cpu until restarted.

I don't know what precisely does this so I dont know how to reproduce.. (so.. its not usefull comment)... but after any bot attack I need to restart bungeecord because it overloads the cpu even after the attack is finished. 

my home made solution was just to throttle new connections from the same ip to 2 seconds in between. can't throttle them all because I normally have a lot of connections since is a big network.

**Comment by Janmm14** [comment]
Is it possible that the cpu overload comes from the half second delay in bungeecord before kicks are done?

**Comment by smartmadio** [comment]
I have collecred some attack tools and made a test today.If the bots just connect in bungeecord,it won't leads to CPU overload and bungeecord could kick the bots after the attack is finished.But if the bots connect in and send some command(such as /reg 12345678) the bungeecord will overload CPU immediately.

**Comment by smartmadio** [comment]
Each bot will cost 5% CPU

**Comment by smartmadio** [comment]
I don't know if is that the cpu overload comes from the half second delay in bungeecord.
A bot connect for only one time will cost 5% CPU.

**Comment by XNoki200010** [comment]
I think the bots are spamming something to overload the BungeeCord.

**Comment by FurmigaHumana** [comment]
@XNoki200010 the bots disconnect very shortly after connecting

**Comment by Janmm14** [comment]
@smartmadio Can you use your bot tools to try out my customization of bungeecord? Download: https://ci.janmm14.de/job/public~server~FlexPipe/
(Before doing your test, please ensure to set connection_throttle to 0 or -1 in config.yml)

**Comment by smartmadio** [comment]
@Janmm14 I'll have a try today.

**Comment by smartmadio** [comment]
@BOT-Neil I've tried this tool 2 days ago,of no use.It's not bot flood,this tool even don't turn to online mode during the attack.

**Comment by smartmadio** [comment]
@Janmm14 Test finished, 5 bots joined in.Each bot join for only one time,this leads to 25% CPU usage.
20 bots joined in 20 minutes (one bot join per minute,join only for one time),this leads to 100% CPU usage.After the attack was stopped,the CPU usage is sitll 100% until I closed FlexPipe manually.

**Comment by Janmm14** [comment]
@smartmadio Okay, no change. I'll look further into this.

**Comment by smartmadio** [comment]
@Janmm14 
I found a strange thing,the commands sent by bots could not be seen in the spigot server underlying bungeecord.

**Comment by smartmadio** [comment]
```
[15:15:33 INFO]: FML1009299684 lost connection: Internal Exception: io.netty.han
dler.codec.DecoderException: Badly compressed packet - size of 3 is below server
 threshold of 256
```
If I remove bungeecord and use this tool to attack the spigot server directly,I'll receive this command.
The spigot server didn't overload CPU and could kick all of them correctly.

**Comment by smartmadio** [comment]
Could it be the badly compressed packet crashed bungeecord?(Bungeecord #1123 also have this problem)

**Comment by Janmm14** [comment]
@smartmadio It might be that the player is not fully connected to the underlying spigot server hwne the bot tool sends the command.

**Comment by smartmadio** [comment]
@Janmm14 It might be.My test shows this kind of attack has no effect on spigot server.It could only crash bungeecord.So there must be some kind of bug in bungeecord,I'd suppose.

**Comment by Janmm14** [comment]
@smartmadio I can't reproduce this (cpu usage goes down again) with a bot tool I know (on localhost). Could you maybe share the tool you have with me? Also are you attacking localhost or have it running on an external server?

**Comment by smartmadio** [comment]
@Janmm14 how to share it with you?Email or other kind of way?

**Comment by Janmm14** [comment]
@smartmadio Either an email at givemebottool@janmm14.de or a private message on spigotmc.org.

**Comment by smartmadio** [comment]
@Janmm14 Already send out.Be sure to test it in virtual machine.

**Comment by KingIngoEP** [comment]
@smartmadio I have the same problem and can you send me the tool for test's? starteaker@googlemail.com

I test my bot protection with the deathbot tool and all work.
https://www.google.de/url?sa=t&source=web&rct=j&url=https://twitter.com/deathbot_&ved=0ahUKEwids4GAxsfLAhWFCw8KHXsWC1YQFggaMAA&usg=AFQjCNHfN48318GUtRw-v99C1SxFfB3pnw&sig2=fCJKLXHloaUZ9WO9w734Xg

**Comment by KingIngoEP** [comment]
@smartmadio do you fix the problem?

**Comment by Janmm14** [comment]
Now working on this issue.

**Comment by Janmm14** [comment]
Invalid compressed data is sent. Per connected bot I get 25% cpu usage (4 cores, so 1 core 100%) on a win 7 machine (Java ZLib). The native zlib has not been looked at.

The bot sends a compressed packet with a size of ```3``` (as you can also see in the error message by @smartmadio) followed by one byte with the value ```1```.
This leads to an infinite loop in the java zlib impl  waiting for new data probably because at decompression of ```1```, the program thinks that something is missing.

The minecraft server checks the size of a compressed packet to be higher than the threshold leading to minecraft servers not using bungee not being vulnerable.

If I implement the little if clause in the PacketDecompressor, all the bots get kicked instantly too.

However this might be a bigger underlying problem with invalid compressed data and the java zlib (atleast).

@md-5 Your thoughts maybe?

Also tagging @KingIngoEP

**Comment by smartmadio** [comment]
Glad to know this.Some online-mode bungeecord servers also have been crashed down during attack,I think they might made new attack tool to attack online-mode servers using this bug.

**Comment by smartmadio** [comment]
@KingIngoEP No

**Comment by Janmm14** [comment]
Bungee on Linux vps:
With native zlib enabled: Bot gets kicked for zlib exception -5 simply.
With native zlib disabled: CPU usage for one core goes to 100% and stays there until bungee force-stop (/end won't stop it)

Also @minecrafter: Your commit should successfully kick everyone for invalid compressed packets.

**Comment by Janmm14** [comment]
Just linking the fix for the failed linked diff: https://github.com/WaterfallMC/Waterfall/commit/ad37f28cdc55672ab3ebeb3897461052a549bb36

**Comment by sfPlayer1** [comment]
I'm reasonably confident that neither minecrafter's nor Janmm14's changes fix this issue.

The actual issue is in BungeeCord's use of Deflater and Inflater. It's only ever checking finished(), but with truncated input that'll never happen. The result of needsInput() has to be taken into account as well.

It should be trivial to exploit the "fixed" implementations by just using a sufficiently long truncated deflate stream and lying in the packet's size field.

The native implementation is also broken in the same way, it just doesn't handle Z_BUF_ERROR properly and exits early. Z_BUF_ERROR is just a notification about needing more input data.

**Comment by Janmm14** [comment]
@md-5 pls see above

**Comment by md-5** [comment]
Thanks @sfPlayer1
