### ISSUE TITLE
End command

### ISSUE THREAD

**Issue by CzlowiekKuktas** [SpigotMC/BungeeCord#1796]
When you type /end test users are still disconnected with default message "Disconnected from the server".

**Comment by kamcio96** [comment]
#1706 fix it

**Comment by CzlowiekKuktas** [comment]
I have to fix this on my own?

**Comment by CzlowiekKuktas** [comment]
@kamcio96 ?

**Comment by kamcio96** [comment]
Hmm? I just send you link to my PR which fix it

**Comment by CzlowiekKuktas** [comment]
So I have to edit it on my own, right?

**Comment by kamcio96** [comment]
yes

**Comment by CzlowiekKuktas** [comment]
I have problems with importing BungeeCord to Eclipse, can you help me?

**Comment by kamcio96** [comment]
no

**Comment by CzlowiekKuktas** [comment]
So how can I fix this?

**Comment by Janmm14** [comment]
Use m2e maven to eclipse plugin.

**Comment by CzlowiekKuktas** [comment]
@Janmm14 I don't know how.

**Comment by Janmm14** [comment]
@CzlowiekKuktas I don't want to link lmgtfy. Its really easy. Install the plugin (if you don't have it) and say eclipse / the plugin that BungeeCord is a maven plugin.

Alternatively you can go for [Waterfall ](https://github.com/WaterfallMC/Waterfall) or [FlexPipe](https://github.com/minotopiame/FlexPipe), forks of bungeecord with various improvements. If you need Forge support, go for Waterfall, otherwise differences are low. They both provide downloads of .jar files.

**Comment by i9hdkill** [comment]
Duplicate of #1387
