### ISSUE TITLE
How do I connect a Vanilla 1.10.2 minecraft server to BungeeCord using VanillaCord?

### ISSUE THREAD

**Issue by djcjf** [SpigotMC/BungeeCord#1961]
Hi there I have bean trying to connect a vanilla 1.10.2 minecraft server to BungeeCord :) But sadly I bean getting some errors I am trying to use VanillaCord right now but I don't know how to use it :( Any help is greatly appreciated thx :D - djcjf

**Comment by Janmm14** [comment]
BungeeCord normally works with vanilla servers.

Please post the errors you get instead of simply moving to another project. Please note that you likely won't recieve any help with vanillacord here.

I don't understand why people always say: There are issues! While still not mentioning the exact errors.
Do you expect the developers create a setup and test around all day?
