### ISSUE TITLE
Connect to fallback on server crash

### ISSUE THREAD

**Issue by vb543** [SpigotMC/BungeeCord#2006]
I feel that this was once a feature, but I could be mistaken. 

At the moment, when a player is on a server and it gets restarted or crashes; instead of automatically switching to another server, they're just disconnected from the network. 

I've looked into the priorities and forced default settings but they don't seem to function in the same way a fallback server setting would. 

Any suggestions?

**Comment by md-5** [comment]
This never was a feature; it has been since two weeks ago.
Bungee will move down the priority list if you are disconnected.

@Mystiflow

**Comment by vb543** [comment]
But that is only after the player re-connects manually, correct? There's no automatic fallback to a different server.

**Comment by md-5** [comment]
There is not and never has been a fallback for a disconnect. The reason for this is we cannot be sure what state the server has left the client in. If there is an exception in the connection between the servers, then the transfer will take place cleanly.

**Comment by md-5** [comment]
Also a restart / crash will rarely trigger this since in most cases the player will be kicked. There is an API which plugins such as MoveMeNow which will override this behaviour. It's disingenuous to have a kick not actually kick a player and Bungee by itself cannot tell if its a kick by a staff member or kick because the server is shutting down.
