### ISSUE TITLE
[Bungeecord 1.10] Contains method does not exist.

### ISSUE THREAD

**Issue by IsS127** [SpigotMC/BungeeCord#2030]
Hello,
I'm using bungeecord 1.10 for a plugin that only works for this current build I have.
So I'm making a plugin for my network.
But then.. There is no config contains like the later builds.
So I'm not sure what to do..
I cannot update or the plugin i'm using will break.
I hope there is a solution for this.
Ty.

**Comment by electronicboy** [comment]
needless to say, there is no support provided for older versions, especially when you've worked out that this is no longer a concern inside the latest versions. use get, and check that it actually returns something, if the get method returns null, that means it's empty.
If your plugin also breaks on newer versions, maybe your should fix your plugin instead of using outdated software.

**Comment by IsS127** [comment]
I cant really fix that plugin,
But ty for ur support :D

**Comment by Janmm14** [comment]
Well BungeeCord 1.11 also supports 1.8-1.10

**Comment by IsS127** [comment]
I know that...
