### ISSUE TITLE
Error after upgrading to build #1226 - Failed to find a usable hardware address

### ISSUE THREAD

**Issue by Mineville** [SpigotMC/BungeeCord#2070]
After upgrading bungeecord to build #1226 me and many others get the following SEVERE Error when starting bungeecord:

> 19:57:58 [SEVERE] Feb 16, 2017 7:57:58 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 1c:cb:57:b2:b3:71:f8:fa

 This Error was already reported in 2016, obviously fixed and now appears again.
[Spigot-Forum-Post](https://www.spigotmc.org/threads/failed-to-find-usable-hardware-adress.186343)

**Comment by md-5** [comment]
https://github.com/netty/netty/issues

This would be a netty bug. I can't help you since I cannot reproduce it.
In any case I doubt it would cause issues.

**Comment by md-5** [comment]
I guess you may be using a Docker container or similar in which case the message is known and will go away next time a netty update is released.

**Comment by Mineville** [comment]
I am not using docker. I will open the bug at netty issues.

**Comment by GoadingGoat** [comment]
Get the same message, with the same build.

Running jar file on debian jessie. Don't use docker, usually run within screen, but have tested outside of screen and still get the same message.

Not really asking for help, just adding info. because as md-5 pointed out, it doesn't seem to cause any issues.
