### ISSUE TITLE
error kick players 

### ISSUE THREAD

**Issue by josecuervo2016** [SpigotMC/BungeeCord#2300]
https://pastebin.com/snJ3Wwra   how fix this ?

**Comment by ApocalypsjeNL** [comment]
It's an error caused by ViaVersion, they even supplied the link where to report this error and that's definitely not the issue tracker of BungeeCord but their own issue tracker. Here is the link to it http://github.com/MylesIsCool/ViaVersion/issues

Source: 
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues

**Comment by josecuervo2016** [comment]
Hello thank you for your answer but according to the developer of via version says that it is not your plugin problem
