### ISSUE TITLE
error new  how fix?

### ISSUE THREAD

**Issue by josecuervo2016** [SpigotMC/BungeeCord#2301]
https://pastebin.com/mAt4n3z1

**Comment by ninja-** [comment]
1. You are not using BungeeCord but a fork called Waterfall
2. This is harmless, a random client spamming invalid data

**Comment by josecuervo2016** [comment]
thanks what happens in waterfall do not respond me, I am very beginner in this, I would say that harmless data send? . is something that makes it appropriate to damage the server .. or is it a problem with your computer

**Comment by Black-Hole** [comment]
You can't prevent clients sending whatever data they like. BungeeCord will log this. It's up to you to decide to just ignore this or ban some ip addresses that are spamming your log file while making sure that's not a server pinger from a server list.
Please use the BungeeCord forum on the Spigot forums for community support, since this isue tracker is for bugs and feature requests for BungeeCord, not for support.
For bugs and feature requests for Waterfall, please use the Waterfall issue tracker.

**Comment by md-5** [comment]
>thanks what happens in waterfall do not respond me,
You use our software if you want our support.
