### ISSUE TITLE
PlayerDisconnectEvent not being called

### ISSUE THREAD

**Issue by concuncan** [SpigotMC/BungeeCord#2345]
Hey there,

When a channel is 'abruptly' closed when switching servers and the 'No client connected for pending server!' error is thrown, PlayerDisconnectEvent is never being called.

**Comment by md-5** [comment]
How to reproduce?
Just looking at the code I don't believe this because the disconnect event is called unconditionally from the UpstreadmBridge which is initialized way before ""No client connected for pending server!"" is ever printed.
In fact using a plugin to add a delay and allow this disconnect, we can show this message being printed along with the event:

```
07:43:05 [INFO] [md_5] <-> InitialHandler has connected
>
07:43:05 [INFO] [md_5] <-> ServerConnector [lobby] has connected
>
07:43:08 [INFO] Disconnect event
>
07:43:08 [INFO] [md_5] -> UpstreamBridge has disconnected
>
07:43:10 [WARNING] No client connected for pending server!
>
07:43:11 [INFO] [md_5] <-> ServerConnector [lobby] has disconnected
```
