### ISSUE TITLE
Use another provider for metrics, not MCStats

### ISSUE THREAD

**Issue by DoNotSpamPls** [SpigotMC/BungeeCord#2358]
as we all know, mcstats is essentially dead at this point, it's unstable and doesn't work every time.
My suggestion is to move to another provider, such as bStats, or a custom implementation. Or maybe just remove metrics entirely. Either way, mcstats is not viable anymore as a robust metrics solution

**Comment by md-5** [comment]
Haven't done this here or in Spigot for reasons previously stated - switching metrics wouldn't really provide an accurate picture (although better on Bungee than Spigot, because at least here most are updated), and if we did switch it would have to be to a service we control to prevent future issues.
Having the metrics run in the background and fail silently (which is what it does) doesn't harm the server, which is why its still in at all.

**Comment by Janmm14** [comment]
I would suggest to simply use both proviers.

**Comment by DoNotSpamPls** [comment]
Well, it seems that mcstats.org is going to expire in a few days... rip

**Comment by DoNotSpamPls** [comment]
If "another service is never going to provide an accurate picture", that also counts for your service as well. Until you decide, might as well just remove the metrics - it's not like that new service is coming any time soon 🤔

**Comment by Janmm14** [comment]
what new service?

I don't see a reason to have the ultimate and final solution for some metrics, just use bstats while its there and we'll have a decent view of people using an up-to-date version of bungeecord.

**Comment by DoNotSpamPls** [comment]
@Janmm14 the new self-hosted service md-5 has been talking about for *years* (first mention in 2013, still nothing)

**Comment by md-5** [comment]
Doesn’t matter, my underlying point still stands.
We would only switch to a metrics service we control, even if there are no plans for us to create such a service.
