### ISSUE TITLE
ColorCodes still doesn't work

### ISSUE THREAD

**Issue by YTKacperSKY** [SpigotMC/BungeeCord#2389]
Now the first append work but all further still doesn't work.

Example: https://puu.sh/zI8VG/d12892e5bb.png
i have a method `.newLine()` which appends a `\n` and everything after that breaks like the issue before (#2387)
I use it in my dispatcher and it worked before build #1302
```java
cs.sendMessage(new ComponentBuilder("")
.append(TextComponent.fromLegacyText("§8§m-----------§r§8[ §7Statistiken von §6mir §8]§8§m-----------§r")).append(TextComponent.fromLegacyText("\n"))
.append(TextComponent.fromLegacyText("§8§m-----------§r§8[ §7Statistiken von §6mir §8]§8§m-----------§r")).append(TextComponent.fromLegacyText("\n"))
.append(TextComponent.fromLegacyText("§8§m-----------§r§8[ §7Statistiken von §6mir §8]§8§m-----------§r")).create());

**Comment by Mystiflow** [comment]
I think you need to add ```FormatRetention.NONE``` argument to your appends as it defaults to ALL. This looks like correct behaviour, see javadocs: 
> The components will have all the formatting from previous part.

**Comment by md-5** [comment]
&r is not being carrying through, that looks like a bug to me @Mystiflow

**Comment by Mystiflow** [comment]
I'm not sure supporting legacy colours etc is in the scope of the API though and should really use ```..builder#reset()``` instead. Due to the way ```TextComponent.fromLegacyText``` parses strings, each part of text that is differently coloured is made a new component which makes it so we can't copy the formatting of each previous components.

I can see two possible fixes for the code provided in the issue (text message modified for code readability):
* Change ```.append(TextComponent.fromLegacyText("§8§m---message---").append("\n")``` to ```.append(TextComponent.fromLegacyText("§8§m---message---\n")``` removing the extra new line append, this makes it so the last component has the formatting and will be copied.
* Move the §r to the start of the append: e.g. ```.append(TextComponent.fromLegacyText("§r---message---"))```

**Comment by YTKacperSKY** [comment]
I am wondering why this worked in the first place and which change broke this. I used it for a long time and now I can't find a replace without changing my whole code
