### ISSUE TITLE
Cannot listen to events that are abstract called

### ISSUE THREAD

**Issue by AlessioDP** [SpigotMC/BungeeCord#2694]
_My problem is listening an event that is made via abstract classes._

I have a main event that is an abstract class, for example:
```java
public abstract class SimpleEvent extends Event {
	// Dummy class
}
```
And I call it like this:
```java
ProxyServer.getInstance().getPluginManager().callEvent(new SimpleEventHook());
```
where SimpleEventHook is:
```java
public class SimpleEventHook extends SimpleEvent {
	// All stuff of the event
}
```

I use the same approach to handle Bukkit events and it works, I'm pretty sure that some year ago builds were okay.

**Why I handle them like this?**
The API are only interfaces/abstract classes of my real events, so I can change the code without change the API.

**Comment by Janmm14** [comment]
Bukkit's event system works differently internal.
BungeeCord's event system is depending on the qualified class name only.

**Comment by md-5** [comment]
This is by design.
Bukkit makes each event explicitly add handler methods, and therefore it is up to the event writer to decide whether it is called for the parent class, or only child class. The 'abstractness' of the class is completely irrelevant - it only depends on where the handler list is placed.

Bungee on the other hand does not make each event explicitly have handler methods. The corollary of this is that each event is called explicitly only on the class. To jump upwards would be very slow as each event call would need to check all the parent classes of the event class and fire the registered handlers for them.

> The API are only interfaces/abstract classes of my real events, so I can change the code without change the API.

Events are effectively skeletons anyway; I would call what you're doing over-abstraction - events generally do nothing but expose getters or setters.

>I'm pretty sure that some year ago builds were okay.

Bungee has never called handlers for super classes as far as I know. The current event code is over 6 years old, and before that it was the Google event bus which again I'm sure doesn't call it for parent classes.
