### ISSUE TITLE
Why does Bungee use delayedClose in ServerConnection and UserConnection?

### ISSUE THREAD

**Issue by Janmm14** [SpigotMC/BungeeCord#2713]
Is there any reason why we would want the server connection to get closed with a delay?

I think this can and should be done instantly, because these handlers do not have to fight with slow clients not switching protocols fast enough.

https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/ServerConnection.java#L57

https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/UserConnection.java#L401

**Comment by MrIvanPlays** [comment]
Because minecraft's codebase is old and filled with bad practices and bad code. Same for nms, bukkit, craftbukkit, spigot and bungeecord. Why I think like that? See this explanation for the delayed close: https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java#L106-L108

But why am I blaming them for bad code? If you turn around your head on bukkit's code you'll see a lot of bad practices and that no principle following. NMS has [this](https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/AbstractPacketHandler.java) shit packet handler which bungee has too which violates literally every principle.

**Comment by Janmm14** [comment]
@MrIvanPlays I know about that comment in ChannelWrapper. I was asking for a possible explanation why delayed channel closing exists at places where that comment does not apply.

**Comment by MrIvanPlays** [comment]
Okay, I've did some tests on the topic. There's no reason for a delayed close [here](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/ServerConnection.java#L57). With paper it throwed me [this](https://bin.mrivanplays.com/jfk8k4ZdhON) error whenever I switched the servers, strangely enough this doesn't happen on spigot so perhaps thats a bug with paper or it is that the proxy isn't online mode.

Haven't tested about the user connection delayedClose, but I will test it soon.

**Comment by Fejm** [comment]
Tested & works fine with multiprotocol server
