### ISSUE TITLE
network_compression_threshold

### ISSUE THREAD

**Issue by DanielAlves123** [SpigotMC/BungeeCord#2732]
Can I safely change 'network_compression_threshold' to 128 (default is 256) or 64? Will it have good impact on player's connection and small impact on cpu usage? Thanks for help

**Comment by Janmm14** [comment]
Compression of very small amounts of data very often does not reduce its size, because there is less long similar data inside (if any similar data is found). Lowering it will not benefit players connection and - depending on how much you lower it - it will have impact on cpu usage: because most minecraft packets are already very small, lowering compression threshold too much will lead to a significant increase in packets which will be compressed with no reasonable gain in size reduction.

**Comment by DanielAlves123** [comment]
@Janmm14  Yes, but my question is will changing network_compression_threshold from 256 to 128 be helpful and safe? Will value of 64 be better for players?

**Comment by Janmm14** [comment]
It is safe, but as I wrote, I do not think it will help.

**Comment by kamcio96** [comment]
> Note: The Ethernet spec requires that packets less than 64 bytes become padded to 64 bytes. Thus, setting a value lower than 64 may not be beneficial. It is also not recommended to exceed the MTU, typically 1500 bytes.
