### ISSUE TITLE
Exploit on Bungee found and is being used to crash the proxy

### ISSUE THREAD

**Issue by QueenAngus** [SpigotMC/BungeeCord#2743]
Hi there!

So a user has been crashing my bungee server by sending many (around 50) requests to it every second, this makes it completely unjoinable and spams the console as shown in this log: https://pastebin.com/bHAuRCSy

How can I limit these requests, stop them entirely or fix this issue? He can do it to anyone running bungee which is a big issue as it completely stops it from being useable, restarting it doesn't fix it, you just have to wait for them to stop attacking. 

Thanks.

**Comment by md-5** [comment]
I have not so far seen any evidence that this is the result of some sort of exploit or some sort of thing that Bungee could be handling better. The code before this point in the connection is already minimal and lightweight (and has been in production for years).

You should provide some more information such as a CPU profile or at the very least a TCP dump showing the supposedly problematic packets.

There's also nothing in your log indicating Bungee is 'crashing'. A DoS from 50 IPs could very easily overwhelm a 100mbit or even 1gbit connection and would not be stoppable.

**Comment by Kneesnap** [comment]
I don't know, it seems pretty obvious to me why this is happening. By using exceptions for invalid packets and issues like this, if someone causes a shit ton of exceptions, it would completely bog the CPU.

**Comment by md-5** [comment]
Exceptions for handling exceptional conditions is standard behaviour in Netty (see pretty much any codec https://github.com/netty/netty) and pretty much every other Java server out there.

Do you have some evidence to indicate that the issue here really is throwing an exception?

**Comment by yooniks** [comment]
The exceptions are not a problem, it's normal behaviour. 
PM me on discord: yooniks#0289, i will help you.

**Comment by md-5** [comment]
Right so I've spent the last day and a bit performing extensive benchmarking and performance testing of BungeeCord. Whilst some minor improvements have been made (https://github.com/SpigotMC/BungeeCord/commits/master), I do not see anything to indicate that Bungee has some sort of exploit, or systemic design weakness leading to worse than expected performance.

In all cases my 4 core, 6 year old desktop PC (whilst running the stresser, Minecraft, my IDE, Bungee etc) can handle at least 5,000 requests per second. This number does not change dramatically regardless of what type of 'exploit' is used (I have tested 3-4 different hypothesised 'malicious' packets based on what has been posted on this tracker, they're all within a few hundred rps of each other).

I've also tested various suggestions (eg flush before closing which does nothing - see #2749, removing use of exceptions and replacing with `ctx.close();return`, and flat out disabling console logging). The latter two basically provide on par performance increases which indicates that throwing exceptions is not a bottleneck or 'slow' as some people suggest. Printing less to the console does provide a performance increase, but this is very easily justified -- the performance increase is in the same ballpark as changing the available CPU by 1 core, which is logical given the asynchronous logger. This was validated by only stubbing out the actual IO from the async thread. If you are running a single core server I guess this would be significant, but in a multicore server it is not the difference between bungee staying up and bungee being successfully DoSd. Even when CPU was maxed out by incoming malicious connections, my client was able to connect and play without undue lag. Note: on my system at least changing the priority of the logger thread does not change results.

In summary, based on my testing, given a default configuration of Bungee and modest hardware specifications (~3 cores, 6 year old dedicated CPU) it would take a sustained attack of at least 20,000 IP addresses before there is a significant issue with BungeeCord stability. An attack of 20,000 IP unique addresses is very much a DDoS and there is not much we can do to handle that. A standard nginx+php web server falls over at two orders of magnitude less than that. Note that some users being attacked for whatever reason have disabled their connection throttle (see eg #2764). That of course enables a much easier attack because it would only take a couple of remote IPs to send several thousand requests a second, but that is user error.


--> Based on my testing with available info there is no 'exploit' on Bungee. Bungee handles thousands of requests a second without issue. If you think there is an exploit you need to provide more information (CPU profile, packet captures, etc) that points to this being the case.

**Comment by MrIvanPlays** [comment]
md, have you tried spamming the proxy with invalid handshake packet state? Try it, I DARE YOU

**Comment by md-5** [comment]
>I have tested 3-4 different hypothesised 'malicious' packets based on what has been posted on this tracker, they're all within a few hundred rps of each other


Do you have some useful information to add, or are you just here to troll?

**Comment by MrIvanPlays** [comment]
> > I have tested 3-4 different hypothesised 'malicious' packets based on what has been posted on this tracker, they're all within a few hundred rps of each other
> 
> Do you have some useful information to add, or are you just here to troll?

I don't think what you've tried causes [this](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L347) exception to be thrown. As I said

> have you tried spamming the proxy with invalid handshake packet state? Try it, I DARE YOU

**Comment by md-5** [comment]
>I don't think what you've tried causes this exception to be thrown. As I said

I tried it just now, same of the others (well over 5,000 rps).

Do you have anything else to add other than 'I DARE YOU'? I did you 'dare' and it didn't show anything unexpected. Are you seeing something different?

**Comment by Ste3et** [comment]
md-5 i didn't figured out the problem, it looks like the Bungeecord did receive invalid packets on handshacke and print into console

`
<-> InitialHandler - bad packet ID, are mods in use!? Packet with id 1784785 outside of range
<-> InitialHandler - bad packet ID, are mods in use!? No more bytes reading varint
`

there is a new method in the "hacker" scene and the webservice mcspam.tech sell a working BungeeSmasher for 45£ each MONTH -> https://www.youtube.com/watch?v=oQklwnCpQ_k
i think iptables who limit the incoming requests can fix that issue but my server is to small to leave a review of my changes, a friend have that problem on his network.
I spend my complete weekend on search for a solution to protected the server and figured out how is the method work without any result.

**Comment by Leymooo** [comment]
`well over 5,000 rps`
how many bandwidth needed to handle 5000 rps? I think the main goal of this attacks its use all available bandwidth of server.

**Comment by md-5** [comment]
> <-> InitialHandler - bad packet ID, are mods in use!? No more bytes reading varint

BungeeCord has no such message


><-> InitialHandler - bad packet ID, are mods in use!? Packet with id 1784785 outside of range

Same results as all the other tests.


> how many bandwidth needed to handle 5000 rps? I think the main goal of this attacks its use all available bandwidth of server.

Depends on the specifics, but if the attacker is going just for RPS, not much. If the attacker is going for bandwidth well that's definitely not bungee's issue.

**Comment by ConnorServers** [comment]
I'm not an expert dev. But if BungeeCord has no such message, is this part of the source not apart of bungee?

```
BungeeCord/protocol/src/main/java/net/md_5/bungee/protocol/MinecraftDecoder.java

Line 37 in aaddc9f

 throw new BadPacketException( "Did not read all bytes from packet " + packet.getClass() + " " + packetId + " Protocol " + protocol + " Direction " + prot ); 
(

BungeeCord/proxy/src/main/java/net/md_5/bungee/netty/HandlerBoss.java

Line 104 in d9a8311

 ProxyServer.getInstance().getLogger().log( Level.WARNING, "{0} - bad packet ID, are mods in use!? {1}", new Object[] 
)
```

**Comment by Janmm14** [comment]
Linking specific lines and correcting you a little:

Searching for `bad packet ID, are mods in use!?` shows:
https://github.com/SpigotMC/BungeeCord/blob/e9ba95b9dc70058c5da99639c45200cd230b2d9d/proxy/src/main/java/net/md_5/bungee/netty/HandlerBoss.java#L144-L147
You can see that its getting the message of a `BadPacketException` and appends it to that phrase.

The `BadPacketException` with the message `Packet id xxx outside of range` exists in bungeecord:
https://github.com/SpigotMC/BungeeCord/blob/c2cc33c6d74ceddaf55cb8960ac305920cc41e90/protocol/src/main/java/net/md_5/bungee/protocol/Protocol.java#L427

**However BungeeCord does not create a `BadPacketException` with the message: `No more bytes reading varint`.**
