### ISSUE TITLE
Please avoid using libraries with CVEs

### ISSUE THREAD

**Issue by www-yyy-1** [SpigotMC/BungeeCord#2779]
Hi, I found that your project are using some vulnerable dependencies. I suggest updating their versions to increase the security of your project. The following is a detailed content.
* **Vulnerable Library Version:** mysql : mysql-connector-java : 5.1.48
  **CVE ID:** [CVE-2019-2692](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-2692)
  **Import Path:** proxy/pom.xml
  **Suggested Safe Versions:** 8.0.16, 8.0.17, 8.0.18, 8.0.19
* **Vulnerable Library Version:** com.google.guava : guava : 21.0
  **CVE ID:** [CVE-2018-10237](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10237)
  **Import Path:** module/cmd-alert/pom.xml, module/cmd-list/pom.xml...(The rest of the 18 paths is hidden.)
  **Suggested Safe Versions:** 24.1.1-android, 24.1.1-jre, 25.0-android, 25.0-jre, 25.1-android, 25.1-jre, 26.0-android, 26.0-jre, 27.0-android, 27.0-jre, 27.0.1-android, 27.0.1-jre, 27.1-android, 27.1-jre, 28.0-android, 28.0-jre, 28.1-android, 28.1-jre, 28.2-android, 28.2-jre

**Comment by md-5** [comment]
CVE-2019-2692 is irrelevant as far as I can tell. It would also be surprising if it did exist because as far as I know the 5.1.x train is still supported by Oracle and 5.1.48 is the latest version.

The Guava 'vulnerability' does not affect BungeeCord, the Java Object serialization API is broken and no one should use it, let alone on untrusted data. We have specific reasons for pinning this version.
