### ISSUE TITLE
keepalive queue polling problem

### ISSUE THREAD

**Issue by Janmm14** [SpigotMC/BungeeCord#2783]
See discussion here:
https://github.com/SpigotMC/BungeeCord/commit/eeb374798b10786bb87175796b55bed0275d56c7#commitcomment-37700213

We have to use peek() first to get the keepalive number to compare to, and only call poll if it fits.

Otherwise, as long as the queue never empties (happens when many keepalives are sent or connection has great latency), we are at least off by one keepalive until next server switch.

**Comment by MrIvanPlays** [comment]
Actually looking at your original code, you do this.
https://github.com/Janmm14/BungeeCord/blob/fix-keepalive-handling/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L121-L124

Also it seems you're using LinkedList and not Queue
https://github.com/Janmm14/BungeeCord/blob/fix-keepalive-handling/proxy/src/main/java/net/md_5/bungee/ServerConnection.java#L33

**Comment by MrIvanPlays** [comment]
https://github.com/SpigotMC/BungeeCord/pull/2786#issuecomment-598031817

**Comment by Janmm14** [comment]
Yey, so I did implement it correctly, but it was not my pr which got merged in the end.

**Comment by FurmigaHumana** [comment]
We run a custom fork of BungeeCord on our end, when I applied this changes to our fork I imediatly noticed a substantial ping average increase and a lot of random spikes (only on the getPing method, not affecting the actual gameplay), reverting just that change fixed the issue, on further investigation we applied a similar fix to what @MrIvanPlays suggested and it seems to have improved.

However with no apparent benefit the extra cost of this method was not worth it, we reverted back to how it used to be which seems to give a more consistent result and precise enough for what it does

**Comment by Janmm14** [comment]
@FurmigaHumana If you reverted back to before saving multiple pings then bungee and spigot doesn't measure ping of people with a ping greater than 1000 and both will stick to their last ping value before the ping spike of the player.

**Comment by FurmigaHumana** [comment]
Yes I am aware, but for our case since we only use it as a misc command for players to check their own ping it dosn't really matter how acurate it is as long as its close enough, anyways that is not the point

---


I ran some tests and I think there's actually nothing wrong, the new methods just started showing the actual average latency given it wasn't counting the really laggy players or latency spikes before. 

https://i.imgur.com/6IZxl32.png

The red area is the code bungeecord is using currently, green area is the older implementation which does not save multiple pings, the black area is a mix, some servers are running the fix suggested above, some my own fix, and some your original pr, all showing the same average pings (a little higher today because is friday)

 I guess the new method just show the reality of hosting your server 7000 miles away from you.

**Comment by md-5** [comment]
#2786
