### ISSUE TITLE
bad packet

### ISSUE THREAD

**Issue by markusmarkusz** [SpigotMC/BungeeCord#3021]
Our server is getting crashed by invalid packets.
error message:
```
InitialHandler - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.EncryptionResponse 1 Protocol LOGIN Direction TO_SERVER
```
the corresponding part in our log file: https://gist.github.com/markusmarkusz/c08a68050cf02e9c86396beb0d5e2c9c

The question: Will that be fixed by you or do we have to come up with something ourselves, since that just happens when we receive such packets?

**Comment by fikawka** [comment]
No, it wont be fixed, because there was ton of threads like those. ,,LOGIN Direction TO_SERVER" so i assume its the handshake exploit, try to maybe make ip tables? It should make those attacks less efficient. Try to limit connections per IP, and connections per second global maybe, and let us know the results. Also there are many BungeeCord forks,  that are created to fight with this

**Comment by markusmarkusz** [comment]
In my opinion, this is a bug in BungeeCord because it's an invalid packet that triggers the crash.
Ideally, the proxy verifies whether the content of a packet is valid and, if not, it's filtered and the server isn't killed.
But at the moment it receives the packet and then shuts down the proxy after kicking every user with "network restart"

**Comment by Janmm14** [comment]
Use Waterfall, they fixed this unneccessary CPU usage caused by this packet.

No, its not a packet which shuts down bungeecord, it might get overloaded and then some program on your VPS decides to stop BungeeCord, causing it to kick all players. At least thats my theory.

**Comment by markusmarkusz** [comment]
I don't think the CPU usage is the issue. The entire server load is constantly low.

The main issue is that the characters sent are all apparently UTF-16 characters and it seems like BungeeCord cannot process these packets. This is in my opinion an issue that should be officially fixed.

Saying "Use Waterfall" might solve the problem on our side, but the bug in BungeeCord persists. But at the moment I'm not sure if Waterfall really has a bugfix for this.

**Comment by Janmm14** [comment]
It makes no sense that any input sent to bungeecord causes crashing in a way that you dont get a stacktrace and causing bungeecord shutting down gracefully.

**Comment by fikawka** [comment]
Okay so did you make an iptables? I tried, that exploit, i downloaded from somewhere on internet one and tested it. It didnt have an option to use proxies. I had crasher, spigot, and bungeecord on my localhost. The server was lagging as crazy, even the spigot was (but maybe because my pc, was overwhelmed not sure), but the main part is that bungeecord was spamming like crazy. 
So what i think, you should do is make an proper iptables if you havent already, because many of these public exploits dont have an proxy option so just limit to 2 connections per second per ip. And connections globally, also you should limit if you dont run server as big as hypixel. And there is also a  problem on BungeeCord side. It is ridiciolous how those exploits spam the console. Also i believe, one good fix would fix most of those exploits, if not all, because they all are really similar. Even 30 connections per like second spam the console way too much, also this might lag, bad disks if someone doesnt have ssd, on their server, OR if they have very limited, space attacking for maybe few hours could fill the disk. (if bungeecord, is logging full logs.

**Comment by Leymooo** [comment]
This attack causes memory leak. There are 2 ways to fix it.
1) Limit string lenght when reading.
2) Dont pass InitialHandler object to Logger#log.

https://github.com/Leymooo/BungeeCord/commit/c4dd63b6cbd6b464a1d48f1d60c9674e5d9b113f
(I dont know why pastebin was removed, but it same as gist above).

**Comment by markusmarkusz** [comment]
> So what i think, you should do is make an proper iptables if you havent already, because many of these public exploits dont have an proxy option so just limit to 2 connections per second per ip. And connections globally, also you should limit if you dont run server as big as hypixel. And there is also a problem on BungeeCord side. It is ridiciolous how those exploits spam the console. Also i believe, one good fix would fix most of those exploits, if not all, because they all are really similar. Even 30 connections per like second spam the console way too much, also this might lag, bad disks if someone doesnt have ssd, on their server, OR if they have very limited, space attacking for maybe few hours could fill the disk. (if bungeecord, is logging full logs.

We receive such attacks from hundreds to thousands of ip addresses. Limiting the connections per ip would'nt really help us.
All ip addresses are proxies from all around the world. Brazil, South Korea, Bosnia Herzegovina, etc. - almost everywhere

**Comment by astei** [comment]
3d701fb should fix the string length issue

**Comment by fikawka** [comment]
@markusmarkusz  sorry for pretty late response, Try to block countries in iptables that dont play on your server normally at all. For  example, if your server is in Germany, and you dont expect people from China, block it.
Block countries that dont play on your server. Will probably help a lot, the attacker will have to buy specific region proxies / or download the ones in internet, but if you don't live in a really big country (like USA, India, China etc), you might be slowly blocking all those public ip adresses, just download them from one website and block all of them. If attacker is attacking then from for example 20, 30 ip adresses, go ahead and block them in iptables, and he will run out of proxies, unless you live in a big country, or attacker buys paid proxies like 5000 of them, then it won't help.
Also i am not sure if i recommended global connections per second, i mean it would fix the problem but attackers could abuse it and block access to the server so thats not good.

**Comment by markusmarkusz** [comment]
@fikawka
Geo blocking is extremely inefficient, especially since ip addresses can change hands too. Thanks to this system, I have already been blocked on various websites & co. My Google help page was even in hebrew, while other websites blocked me because I had a turkish ip.

Using iptables is therefore extremely time-consuming and high-risk to block innocent users.

**Comment by markusmarkusz** [comment]
https://github.com/SpigotMC/BungeeCord/commit/3d701fbe0ec690d83c10487c57e7dbff353fb0d7 fixed the issue, so I'll close this.

**Comment by Janmm14** [comment]
When I managed a server, I've taken some time now and then to gather ips of public proxies. Ihere are many results on free socks proxy on google. Then I used a simple script to remove the port from those lists and deduplicate the entries and then you can feed it into iptables or some bungee ip block plugin.
