### ISSUE TITLE
Error return packet with scoreboard methode

### ISSUE THREAD

**Issue by TheCalypso** [SpigotMC/BungeeCord#3076]
Hello,
I am doing this issue because I have a little problem when I use a Bungeecord method. Here is the code I wrote:
var objective = new ScoreboardObjective(sbname, title, ScoreboardObjective.HealthDisplay.INTEGER, (byte) 0);
        player.unsafe().sendPacket(objective);

Here is what is displayed in the customer logs:
Unknown custom packed identifier: minecraft:register

Here is the error message when trying to connect to the server:
![image](https://user-images.githubusercontent.com/33781244/116584189-6512b980-a917-11eb-8ba5-e94a8af582f5.png)

(I use last version of Bungeecord)
Can you give us some advice? Good end of the day to you!

Calypso_

**Comment by Janmm14** [comment]
I guess your title is not json chat

**Comment by TheCalypso** [comment]
Hello !
Thank you for your reply. I can not understand, I rely on this topic which works very well for him. Can you give me more information?

https://www.spigotmc.org/threads/scoreboard-with-bungeecord.406682/?__cf_chl_jschl_tk__=f0e78e920a259bff0ae0340030afcc279c1c8288-1619729695-0-AVSXlzj-HxNTR5GnWjptCxphZ2Aq6cKqqNu2mw4CsCXHe7n-tGWFpEmENwqYc54xU3ZviXpufqA8rbV5CwzY1AYRpyUV0hZfTSCpyky4vMpEbpiCYumAc2p6myUFzAc-bsuDrlp-VigUEeKCG3S8vCh5ilK2dgHko2QBrJKKEvmOm807up00mauo1e-4mHVTVfACB5mUoy5UKwTVvsV2zlU9d-ggMhHWh6VHoSv2cgDGQpdtyNo_xaoo7xb7zF11wTkzRqCa5P1HhAM2WncvcgsuquUi_8hkjrU1eKimp7K4rM80HAX-tcIGDs5UdQJo5iE1aMQ-u5fXnZLZTbrR1ykda_A2HbxqfSbL6wEFfGw_mHcSeigPin9NkuaTzOGnuEqU6WavRr3JmrTP3z275ZjlVJA9TkS2dmTonO209_jJ94fKXn4Odt4WXk6ea5PvirLAxT5yUC4LgkJ7wo08IR8

Good end of the day to you!

Calypso_

**Comment by Black-Hole** [comment]
Newer Minecraft versions are using JSON text instead of legacy strings with embedded color codes.
So you have to use JSON strings directly. Or use [ComponentSerializer](https://ci.md-5.net/job/BungeeCord/ws/chat/target/apidocs/net/md_5/bungee/chat/ComponentSerializer.html) to convert BaseComponent[] to a JSON string or even use [TextComponent.fromLegacyText](https://ci.md-5.net/job/BungeeCord/ws/chat/target/apidocs/net/md_5/bungee/api/chat/TextComponent.html#fromLegacyText-java.lang.String-)

Anyway, sending packets directly is not part of the API. There are classes for working with scoreboards in [net.md_5.bungee.api.score](https://ci.md-5.net/job/BungeeCord/ws/api/target/apidocs/net/md_5/bungee/api/score/package-summary.html)

For further help please ask at the Spigot forums.
