### ISSUE TITLE
SLF4J broken

### ISSUE THREAD

**Issue by KotlinFactory** [SpigotMC/BungeeCord#3084]
Recent versions of BungeeCord are now containing an org.slf4j implementation.

![slf4j implementation](https://user-images.githubusercontent.com/49833472/117793063-2a305000-b24c-11eb-893f-89f1cc559572.png)

However, this implementation seems to be broken.
On a plain plugin, not shading SLF4J this happens:

```java
Logger testLog = LoggerFactory.getLogger("Example");
testLog.info("Example message!");
```

Results in:

```
11:27:44 [SERVE] Mai 11, 2021 11:27:44 AM CLASS_NAME METHOD_NAME
INFORMATION: Example message!
```

**Comment by Exceptionflug** [comment]
> 
> 
> slf4j is not part of the bungeecord API

Slf4j is getting shaded into the final jar file.
![image](https://img.exceptionflug.de/WinRAR_z73tbDeG2F.png)

This alone breaks the logging of some plugins which self contain any slf4j binding. When you are shading Slf4j components, please also provide a functional LoggerFacvtory for Slf4j. For example like this: https://github.com/Simplix-Softworks/SimplixCore/blob/3e08e87e327c7b06c82ed05bb79f4336c8955679/simplixcore-minecraft/simplixcore-minecraft-bungeecord/simplixcore-minecraft-bungeecord-slf4j/src/main/java/dev/simplix/core/minecraft/bungeecord/slf4j/BungeeLoggerFactory.java#L10

This class creates a bridge to the `java.util.logging.Logger` instance returned by `ProxyServer.getInstance().getLogger()` so that Slf4j uses the BungeeLogger.
