### ISSUE TITLE
Pipline in nothing

### ISSUE THREAD

**Issue by PhantomClone** [SpigotMC/BungeeCord#3086]
This is probably the wrong title, but I would like to add a delay if a player changes the server, the player is first ~ 1 second in the "void".

First of all, I would like to know whether this is even feasible.
Then whether it is possible to do the whole thing without making a separate fork.

I have already tried a few things, such as removing the packethandler in the HandlerBoss class, or replacing it with an UpstreamBridge.

One possible solution would be to create a fake minecraft server, which just simultan to be a real server and hole the Player for the 1second. But this an solution which i do not rly like implement.

Does anyone have a solution to my problem? (Maybe to add handler in the player pipline and just clear incoming packets, idk)

**Comment by Janmm14** [comment]
I don't know why you'd ever want to slow down server changing.
To me this looks like a https://xyproblem.info/

**Comment by abhiram555** [comment]
are you trying to block bots attack?, seems to me like the bungee fork aegis does

**Comment by PhantomClone** [comment]
I dont really want any attention.

This 1 second isnt fixed. It depends on fast the in memory db is use is, but i should really take longer then a second.

So if a player quits a server, all relevent data have to be saved and then the player is allowed to join the next server. 

That is my goal.

**Comment by Janmm14** [comment]
Save data when it changes or wait on new server 1-2 seconds before loading data and freeze the player.
Or force to save the data just before actually sending the player change in the server switch command etc.

There is no good way of leaving the player inbetween two servers for extra time due to how bungeecord is programmed (you are disconnected from old server in bungeecord always after the new connection was successfully started).

Clearing the (netty) pipeline is definitely not a possible way to do this.

**Comment by PhantomClone** [comment]
Okay thank you. I guess you are right and there is no smart way with out making a Forke of bungeecord.
