### ISSUE TITLE
UUID Spoof

### ISSUE THREAD

**Issue by Crowraw** [SpigotMC/BungeeCord#3180]
Everything is written here: https://github.com/wodxgod/Griefing-Methods/blob/master/Exploitation/UUID%20Spoofing.md
You can spoof your UUID in offline servers, which is a huge issue

**Comment by Janmm14** [comment]
md_5 and spigotmc are well aware of it and there are multiple places where we warn people about it and provide multiple countermeasure options.

Take a look at the readme section **Security warning** for example: https://github.com/SpigotMC/BungeeCord#security-warning

Also the underlying issue is not inside bungeecord, but inside spigot. And spigot does warn on startup about this as well.

**Comment by md-5** [comment]
Did you even read the document you linked?

> UUID spoofing is not a bug in the server software or protocol. The way Spigot handles the login handshake packets is intended.
