### ISSUE TITLE
Proxy commands cause 'Chat message validation failure' kick with Paper

### ISSUE THREAD

**Issue by Travja** [SpigotMC/BungeeCord#3486]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.1-SNAPSHOT:9f5ace9:1718

### Server version

git-Paper-68 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 5de0f8a)

### Client version

1.20.1, 1.19.4

### Bungeecord plugins

None

### The bug

When running Paper (Spigot itself is fine) behind a Bungee (or Waterfall) proxy, you can get kicked for 'Chat message validation failure' by performing the following workflow:

1. Send chat message
2. Perform a proxy command (`/server`, `/bungee`, etc)
3. Send another chat
4. Kicked

I have reported this over on PaperMC/Paper#9463 but was told that this is likely a proxy issue and not a Paper one. Possibly related--it also appears that cancelling a ChatEvent on the proxy-level will produce a kick on the next message (on Paper or Spigot).

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
If spigot itself is fine how can this be an proxy issue?
If it works with spigot it has to be a paper issue not a bungee issue. Maybe check the paper changes anf look for the chat handling

**Comment by Travja** [comment]
> Paper restores the chat system to working how it should, hence why you don't see this kick; as before, I'm fairly convinced this is a proxy issue and not a paper issue

**Comment by md-5** [comment]
I don't see what bungee can do about this or what can be done aside from disabling chat validation on the server.

You can't have a proxy and strict chat validation - as soon as a message or command is intercepted by the proxy (eg, as a result of using a proxy command), the validation is broken. That's by design and the purpose of the validation system.

The only thing bungee could do is also send the command to the backend server, which would result in an unknown command error on the server every time a proxy command is used. This is obviously undesirable and doesn't solve the event cancellation issue.

**Comment by Travja** [comment]
I absolutely agree. What's interesting about this scenarios is that the `enforce-secure-profile` setting is turned off on both the proxy and the server, so as I understand it, this validation shouldn't even really be getting in the way anyway. I'm also not familiar at all with how Bungee interception works and how that would coordinate at all with how Paper attempts to validate chats/commands.

I'll bring this back up with Paper and see what their thoughts are. Ultimately, this can be worked around using FreedomChat, so it's not a critical bug.
