### ISSUE TITLE
Exception in thread "main" BungeeCord will not start

### ISSUE THREAD

**Issue by michaeldriskell** [SpigotMC/BungeeCord#537]
console shows me this:
03.08 05:11:44 [Server] SEVERE at java.util.HashMap$Entry.hashCode(HashMap.java:818)
03.08 05:11:44 [Server] SEVERE at java.util.AbstractMap.hashCode(AbstractMap.java:494)
03.08 05:11:44 [Server] SEVERE at java.util.HashMap$Entry.hashCode(HashMap.java:818)
03.08 05:11:44 [Server] SEVERE at java.util.AbstractMap.hashCode(AbstractMap.java:494)
03.08 05:11:44 [Server] SEVERE at java.util.HashMap$Entry.hashCode(HashMap.java:818)
03.08 05:11:44 [Server] SEVERE at java.util.AbstractMap.hashCode(AbstractMap.java:492)
03.08 05:11:44 [Server] SEVERE at java.util.HashMap$EntrySet.iterator(HashMap.java:1050)
03.08 05:11:44 [Server] SEVERE at java.util.LinkedHashMap.newEntryIterator(LinkedHashMap.java:419)
03.08 05:11:44 [Server] SEVERE at java.util.LinkedHashMap$EntryIterator.<init>(LinkedHashMap.java:412)
03.08 05:11:44 [Server] SEVERE at java.util.LinkedHashMap$EntryIterator.<init>(LinkedHashMap.java:412)
03.08 05:11:44 [Server] SEVERE at java.util.LinkedHashMap$LinkedHashIterator.<init>(LinkedHashMap.java:366)
03.08 05:11:44 [Server] SEVERE at java.util.LinkedHashMap$LinkedHashIterator.<init>(LinkedHashMap.java:366)
03.08 05:11:44 [Server] SEVERE java.lang.StackOverflowError
03.08 05:11:44 [Server] SEVERE Exception in thread "main" 
03.08 05:11:44 [Server] INFO Enabled BungeeCord version git-BungeeCord-Proxy-1.6.2-SNAPSHOT-"fb94612"-610

I checked the config with a yaml parser so the config is not incorrectly typed
I'll post it anyways.

config.yml:

groups:
  michaeldriskell:
- admin
  disabled_commands:
  - find
    player_limit: -1
    stats: 640a134f-9ebd-41e1-9633-d05ed75b4b6d
    permissions:
    default:
- bungeecord.command.server
- bungeecord.command.list
  admin:
- bungeecord.command.alert
- bungeecord.command.end
- bungeecord.command.ip
- bungeecord.command.reload
  listeners:
  - fallback_server: lobby
    max_players: 400
    host: 192.99.2.42:25565
    tab_size: 60
    force_default_server: true
    tab_list: GLOBAL_PING
    motd: '&9Splash &fNetwork - &41.6.2'
    default_server: lobby
    forced_hosts:
    pvp.md-5.net: pvp
    timeout: 30000
    connection_throttle: 4000
    servers:
    lobby:
    address: 127.0.0.1:2000
    restricted: false
    motd: '&9Splash &fNetwork - &41.6.2'
    survival:
    address: 127.0.0.1:2001
    restricted: false
    motd: '&9Splash &fSurvival - &41.6.2'
    creative:
    address: 127.0.0.1:2002
    restricted: false
    motd: '&9Splash &fCreative - &41.6.2'
    factions:
    address: 192.95.9.25:25565 
    # ^^^^^^^^^^^^^^^^^ This server is hosted on a different server, I don't think its
    # ^^^^^^^^^^^^^^^^^ the problem because it was working earlier with no problems
    restricted: false
    motd: '&9Splash&fPvP - &41.6.2'
    online_mode: true

The only information that I can provide that might be a problem is that I tried installing a few plugins then restarted it and its been crashing since. I removed the plugins and it still keeps crashing so I have no idea what the problem is.

**Comment by GoLogOut** [comment]
C:\Users\liemvo\Desktop\BungeeCords>java -Xms528M -Xmx528M -jar BungeeCord.jar -
o true
16:00:34 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
stalled.
16:00:34 [INFO] Using standard Java compressor. To enable zero copy compression,
 run on 64 bit Linux
16:00:34 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT
:"cc3a8c0":1071
16:00:35 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
lert.jar, provider=JenkinsModuleSource())
16:00:35 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
nd.jar, provider=JenkinsModuleSource())
16:00:35 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
st.jar, provider=JenkinsModuleSource())
16:00:35 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
nd.jar, provider=JenkinsModuleSource())
16:00:35 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
server.jar, provider=JenkinsModuleSource())
16:00:35 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
reconnect_yaml.jar, provider=JenkinsModuleSource())
16:00:35 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"cc3a8c
0":1071 by SpigotMC
16:00:35 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"cc3a8c
0":1071 by SpigotMC
16:00:35 [INFO] Loaded plugin RedisBungee version 0.3.7-SNAPSHOT by tuxed
16:00:35 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"cc3a
8c0":1071 by SpigotMC
16:00:35 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAP
SHOT:"cc3a8c0":1071 by SpigotMC
16:00:35 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"cc
3a8c0":1071 by SpigotMC
16:00:35 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"cc3a8c
0":1071 by SpigotMC
16:00:35 [SEVERE] Exception in thread "main"
16:00:35 [SEVERE] mapping values are not allowed here
 in 'reader', line 40, column 11:
      Factions:
              ^

16:00:35 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(Scann
erImpl.java:871)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(
ScannerImpl.java:360)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(Scann
erImpl.java:226)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingK
ey.produce(ParserImpl.java:558)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserIm
pl.java:158)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserI
mpl.java:143)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode
(Composer.java:226)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Compos
er.java:155)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeDocument(Co
mposer.java:122)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Comp
oser.java:105)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingl
eData(BaseConstructor.java:120)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
16:00:35 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
16:00:35 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:61
)
16:00:35 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.j
ava:59)
16:00:35 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:248)
16:00:35 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLaunc
her.java:54)
16:00:35 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

http://pastebin.com/ZbzqC0Jn

Can you help me? please

**Comment by GoLogOut** [comment]
The pastebin is my config

**Comment by Janmm14** [comment]
http://pastebin.com/diff.php?i=FKN7BGZY

**Comment by Janmm14** [comment]
well you have to compare yourself, pastebin's diff view seem sto be broken (at least for me)

**Comment by minecrafter** [comment]
You have a loose "ip_forward: true" in the middle of a server definition.

Please don't bump old bugs in the future.

**Comment by GoLogOut** [comment]
THX

**Comment by yanchu0612** [comment]
hi i have the same issue and i try all difrent metchods and they dont work!


10:27:50 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
10:27:50 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
10:27:50 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:81de9d5:1221
10:27:50 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
10:27:50 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
10:27:50 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
10:27:50 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
10:27:50 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
10:27:50 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
10:27:50 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:27:50 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:27:50 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:27:50 [INFO] Loaded plugin BuycraftX version 10.1.4 by Buycraft
10:27:50 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:27:50 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:27:50 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:27:50 [ALLVARLIG] Exception in thread "main"
10:27:50 [ALLVARLIG] org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
10:27:50 [ALLVARLIG]     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200)
10:27:50 [ALLVARLIG]     at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
10:27:50 [ALLVARLIG]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
10:27:50 [ALLVARLIG]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:63)
10:27:50 [ALLVARLIG]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:64)
10:27:50 [ALLVARLIG]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
10:27:50 [ALLVARLIG]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
10:27:50 [ALLVARLIG]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
10:27:50 [ALLVARLIG] Caused by: java.nio.charset.MalformedInputException: Input length = 1
10:27:50 [ALLVARLIG]     at java.nio.charset.CoderResult.throwException(Unknown Source)
10:27:50 [ALLVARLIG]     at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
10:27:50 [ALLVARLIG]     at sun.nio.cs.StreamDecoder.read(Unknown Source)
10:27:50 [ALLVARLIG]     at java.io.InputStreamReader.read(Unknown Source)
10:27:50 [ALLVARLIG]     at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:123)
10:27:50 [ALLVARLIG]     at java.io.Reader.read(Unknown Source)
10:27:50 [ALLVARLIG]     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184)
10:27:50 [ALLVARLIG]






ip_forward: true
network_compression_threshold: 256
stats: 57102b43-cc68-4fb9-9d6e-20c9331a5051
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  md_5:
  - admin
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25566
    restricted: false
  survival:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25567
    restricted: false
  MiniGames:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25568
    restricted: false
timeout: -1
listeners:
- query_port: 25577
  motd: '&6Vällkomen till XeonCraft!'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 100
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
