### ISSUE TITLE
"Server is online mode"

### ISSUE THREAD

**Issue by aarongainz** [SpigotMC/BungeeCord#847]
My server has a problem when ever I try and connect to the Bungee server. Its ment to lead me to my lobby, which is on offline mode, as I read might fix the problem. Also my Bungee is on online mode.

**Comment by willotree** [comment]
If anyone is still baffled about this issue here is the fix:
1.In the BungeeCord config file set 'Host' (below 'Fallback server) to 0.0.0.0:25565
2. In all your server.prop files DO NOT Use 25565 as the port. Choose something like 25515. Then in your Bungee config make sure you change the ports under the subject 'Servers' to what you set them in the server.prop file. Hope this helped!

**Comment by 0H4rl3qu1n0** [comment]
Hello I'm still having this issue i have both o- false and offline mode false and connection throttle to -1 but it still wont work

**Comment by Black-Hole** [comment]
Please use the Spigot forum for help configuring your server and your plugins.
